map_type: costmap

obstacle_range: 4.0
raytrace_range: 4.0
robot_radius: 0.0
footprint: [ [-0.2, -0.2], [-0.2, 0.2], [0.4, 0.2], [0.4, -0.2] ] 
inflation_radius: 0.25

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: $(arg laser_frame), data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}
