base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  # Robot Parameters
  holonomic_robot: false
  
  max_vel_trans: 1.0
  min_vel_trans: 0.0
  max_vel_x: 1.0
  min_vel_x: 0.0
  max_vel_y: 0.0  # y is not used
  min_vel_y: 0.0  # y is not used
  max_vel_theta: 1.0
  min_vel_theta: 0.4  # default: 0.6

  # Issue in DWAPlannerROS weighting
  # The planner only consider the goal in the local costmap (fixed in ROS2 DWB)
  # https://answers.ros.org/question/12066/move_basebase_local_planner-maximum-velocity/
  # Acc need to be larger than actual value to reach max vel
  acc_lim_trans: 5.0
  acc_lim_x: 5.0
  acc_lim_y: 0.0  # y is not used
  acc_lim_theta: 5.0

  # Forward Simulation
  sim_time: 3.5  # default: 1.7
  sim_granularity: 0.05  # defaul: 0.025
  vx_samples: 20  # default: 3
  vy_samples: 0  # default: 10
  vth_samples: 40  # default: 20

  # Trajectory Scoring Parameters
  # how much the local planner should stay close to the global path
  path_distance_bias: 32  # default: 0.6
  # how much the robot should attempt to reach the local goal 
  # suggested 20, causing too much violation of the inflation space
  goal_distance_bias: 1.0  # default: 0.8
  # how much the robot should attempt to avoid obstacles.
  occdist_scale: 2.0  # default: 0.01

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  # if the robot ever reaches the goal xy location it will simply rotate in place, 
  # even if it ends up outside the goal tolerance while it is doing so.
  latch_xy_goal_tolerance: true

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
