global_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 2.0  # default: 5
  static_map: true
  
  resolution: 0.01
  width: 30.0  # default: 10
  height: 30.0  # default: 10
