global_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 1.0  # default: 5
  static_map: true
  
  resolution: 0.01
  width: 30.0  # default: 10
  height: 30.0  # default: 10
  
  use dijkstra: false  # default: true
  cost_factor: 3
  neutral_cost: 50
