local_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  static_map: false
  
  resolution: 0.01  # default: 0.05
  width: 5.0  # default: 10
  height: 5.0  # default: 10
  
  rolling_window: true
  
  # for visualization
  publish_frequency: 2.0
  
