controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gopher/left_arm_joint_1
      - gopher/left_arm_joint_2
      - gopher/left_arm_joint_3
      - gopher/left_arm_joint_4
      - gopher/left_arm_joint_5
      - gopher/left_arm_joint_6
      - gopher/left_arm_joint_7
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gopher/right_arm_joint_1
      - gopher/right_arm_joint_2
      - gopher/right_arm_joint_3
      - gopher/right_arm_joint_4
      - gopher/right_arm_joint_5
      - gopher/right_arm_joint_6
      - gopher/right_arm_joint_7